title: CompSci Blogs
description: "August 2023 to June 2024"
owner_name: Nighthawk Coders
baseurl: "/python-pages"
# remote_theme: pages-themes/midnight@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
